### ISSUE TITLE
`Spin`

### ISSUE THREAD

**Issue by blasdfaa** [blasdfaa/gravuety#29]
[Playground](https://gravity-ui.com/components/uikit/spin)
[Source](https://github.com/gravity-ui/uikit/tree/main/src/components/Spin)
[Design](https://www.figma.com/design/66REzL9IJzRfMkCYYnmemn/Gravity-UI-Design-System-(Community)?node-id=43625-493972&m=dev)

**Comment by brokuka** [comment]
Can i take this ?
